// Generate dist/presets.css from the named themes, using the built theme module.
// Runs after `vite build`, so the CSS comes from exactly the code that ships.
import { writeFile } from 'node:fs/promises'
import { THEME_PRESETS, createThemeCss } from '../dist/theme/index.js'

const blocks = THEME_PRESETS.map((preset) =>
  createThemeCss(
    { ...preset.seed, neutralTint: preset.neutralTint, radius: preset.radius },
    {
      selector: `:where([data-theme='${preset.id}'])`,
      darkSelector: `:where(.dark[data-theme='${preset.id}'], .dark [data-theme='${preset.id}'])`,
    },
  ),
)

const css = `/*
 * Shining UI — named themes. Apply with data-theme on any element:
 *   <html data-theme="ember">   or   <section data-theme="slate">
 * Generated by scripts/generate-presets.mjs. Ids: ${THEME_PRESETS.map((p) => p.id).join(', ')}
 */
@layer theme, base, components, utilities;
@layer base {
${blocks.join('\n')}
}
`

await writeFile(new URL('../dist/presets.css', import.meta.url), css, 'utf8')
console.error(`css -> dist/presets.css (${THEME_PRESETS.length} themes)`)
